name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (or not).
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

version: 2.3.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/dio
  dio: ^4.0.0
  # https://pub.dev/packages/hive
  hive: ^2.0.3
  # https://pub.dev/packages/moor
  moor: 4.1.0
  # https://pub.dev/packages/path
  path: ^1.8.0
  # https://pub.dev/packages/uuid
  uuid: ^3.0.1

dev_dependencies:
  # https://pub.dev/packages/moor_generator
  moor_generator: 4.1.0
  # https://pub.dev/packages/build_runner
  build_runner: ^2.0.1
  # https://pub.dev/packages/pedantic
  pedantic: ^1.11.0
  # https://pub.dev/packages/sqlite3flu
  sqlite3: ^1.0.0
  # https://pub.dev/packages/test
  test: ^1.16.8
